/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TetrisRouteImport } from './routes/tetris'
import { Route as IndexRouteImport } from './routes/index'

const TetrisRoute = TetrisRouteImport.update({
  id: '/tetris',
  path: '/tetris',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tetris': typeof TetrisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tetris': typeof TetrisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tetris': typeof TetrisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tetris'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tetris'
  id: '__root__' | '/' | '/tetris'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TetrisRoute: typeof TetrisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tetris': {
      id: '/tetris'
      path: '/tetris'
      fullPath: '/tetris'
      preLoaderRoute: typeof TetrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TetrisRoute: TetrisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
